src/main/java/com/hollingsworth/arsnouveau/api/spell/SpellResolver.java

Remove SpellResolver printlns

---

src/main/java/com/hollingsworth/arsnouveau/common/network/PacketSetBookMode.java

Server side doesn't look in the off hand for the spellbook when a set mode message comes in.

Make spellbook radial menu work in off hand

---

src/main/java/com/hollingsworth/arsnouveau/setup/APIRegistry.java

Removed Debug Line

---

src/main/java/com/hollingsworth/arsnouveau/common/event/EventHandler.java
src/main/java/com/hollingsworth/arsnouveau/common/items/VoidJar.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectPickup.java

Little bit of refactoring to make this simpler to pull off, but should close #91.

Fix pickup glyph ignoring void jar

---

src/main/java/com/hollingsworth/arsnouveau/common/block/SummoningCrystal.java
src/main/java/com/hollingsworth/arsnouveau/common/block/tile/SummoningCrystalTile.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/EntitySylph.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/EntityWhelp.java
src/main/java/com/hollingsworth/arsnouveau/common/items/WhelpCharm.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectInvisibility.java
src/main/java/com/hollingsworth/arsnouveau/setup/APIRegistry.java
src/main/java/com/hollingsworth/arsnouveau/setup/BlockRegistry.java

Fix typoed class names

---

src/main/resources/META-INF/mods.toml

This is to prevent console spam when loading the mod.
Here's said console spam:
```[13:23:37] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [ars_nouveau] Starting version check at http://myurl.me/
[13:23:37] [Forge Version Check/WARN] [ne.mi.fm.VersionChecker/]: Failed to process update information
java.io.IOException: Server returned HTTP response code: 403 for URL: http://myurl.me/
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_261] {}
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_261] {}
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_261] {}
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) …
```

Remove unused URLs

---

src/main/resources/data/forge/tags/items/storage_blocks.json

part 1/2
Sorry for the double PRs, I was lazy and did this in the GitHub Editor :P

forge:storage_blocks tags for Mana Gem Block

---

src/main/java/com/hollingsworth/arsnouveau/client/gui/book/GuiSpellBook.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/validation/SpellPhraseValidator.java

* Fixed hiding all forms and augments when searching
* Fixed some inconsistent states when searching
* Fixed being unable to fade out augment glyph buttons

GuiSpellBook: Fixed some UI bugs

---

src/main/java/com/hollingsworth/arsnouveau/common/entity/EntitySylph.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/goal/sylph/GenerateDropsGoal.java
src/main/resources/data/ars_nouveau/tags/items/sylph/denied_drop.json
src/main/resources/data/forge/tags/items/seeds.json
src/main/resources/data/forge/tags/items/seeds/mana_bloom.json

add tag #arsnouveau:sylph/denied_drop
add missing tags for mana bloom seeds

properly stop sylphs generating dirt

---

src/main/java/com/hollingsworth/arsnouveau/client/gui/book/GuiSpellBook.java

Validation in the spell book GUI ignored gaps in the spell, instead validating the spell parts as though they would be added to the *end* of the spell.  This would result in augments that are valid for the gap but invalid for the end of the spell being faded out
Fixes #265

Spell Book Gui: Fixed a bug where validations failed to account for gaps in the spell

---

src/main/resources/assets/ars_nouveau/animations/drygmy_animations.json

Possible fix for item #323 
Fixed typo in drygmy_animations.json that was causing molang exception on startup

Fixed typo in drygmy_animations.json

---

src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectSummonSteed.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectSummonVex.java

Swapped world.addFreshEntity with the call that fires a summon event

Summon Events on Vex and Steed

---

src/main/java/com/hollingsworth/arsnouveau/common/entity/EntityAllyVex.java

Filled the interface methods to set and get the uuid from entity data. Tested with the summoning focus, potion buffs and self/orbit seems to work now

Fix EntityAllyVex.java

---

src/main/java/com/hollingsworth/arsnouveau/client/renderer/item/SpellBookRenderer.java
src/main/resources/META-INF/mods.toml

Not sure why it worked for me last night but here you go.

1.16.5 Fixes

---

src/main/java/com/hollingsworth/arsnouveau/api/enchanting_apparatus/EnchantingApparatusRecipe.java
src/main/java/com/hollingsworth/arsnouveau/common/datagen/ApparatusRecipeBuilder.java

Added an optional flag to keep the enchantments of the reagent on the result of an Enchanting Apparatus Recipe.

Optional Flag to keep the Enchantments of the reagent on the result

---

src/main/java/com/hollingsworth/arsnouveau/common/block/SummonBlock.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectColdSnap.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectCrush.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectFlare.java

Added method in SummonBlock to allow use with DeferredRegisters. (setRegistryName would lead to an exception)
Change to Damage Sources to "fix" death message, little cleanup (pattern variables ftw)

Small fixes

---

src/main/java/com/hollingsworth/arsnouveau/client/gui/book/GuiSpellBook.java
src/main/java/com/hollingsworth/arsnouveau/client/gui/buttons/CraftingButton.java

Definitely not my best work, but I'm kind of scared of breaking things with aggressive removals.
And it works and gets the job done.

CraftButtons respect ItemRender

---

src/main/java/com/hollingsworth/arsnouveau/api/ArsNouveauAPI.java
src/main/java/com/hollingsworth/arsnouveau/api/RegistryHelper.java

This is the option where Ars would keep registering configs for addons, like it sometimes does now.

Fix issue #495

---

src/main/java/com/hollingsworth/arsnouveau/common/datagen/BlockTagProvider.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectBreak.java

dadobugbedrockores compatibility

---

src/main/java/com/hollingsworth/arsnouveau/common/items/SpellBook.java

Fixed offset for radial menu with item rendering

---

src/main/java/com/hollingsworth/arsnouveau/ArsNouveau.java
src/main/java/com/hollingsworth/arsnouveau/api/event/EffectResolveEvent.java
src/main/java/com/hollingsworth/arsnouveau/api/spell/SpellResolver.java
src/main/java/com/hollingsworth/arsnouveau/client/gui/utils/RenderUtils.java
src/main/java/com/hollingsworth/arsnouveau/common/armor/Materials.java
src/main/java/com/hollingsworth/arsnouveau/common/datagen/ApparatusRecipeBuilder.java
src/main/java/com/hollingsworth/arsnouveau/setup/BlockRegistry.java

Added resolver to effect event.
Added colors to leaves, so maps can recognize them.
Add withSource to apparatus builder
Added Magebloom seed to compostable

Misc stuff

---

src/main/java/com/hollingsworth/arsnouveau/common/entity/goal/amethyst_golem/HarvestClusterGoal.java

#599 Signed-off-by: Alexthw46 <77152778+Alexthw46@users.noreply.github.com>

Fixed Amethyst bug #599

---

build.gradle
src/main/java/com/hollingsworth/arsnouveau/api/spell/SpellTier.java
src/main/java/com/hollingsworth/arsnouveau/client/ClientHandler.java
src/main/java/com/hollingsworth/arsnouveau/common/datagen/BlockTagProvider.java
src/main/java/com/hollingsworth/arsnouveau/common/datagen/ItemTagProvider.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/AmethystGolem.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/goal/amethyst_golem/GrowClusterGoal.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/goal/amethyst_golem/HarvestClusterGoal.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/goal/amethyst_golem/PickupAmethystGoal.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectPhantomBlock.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/method/MethodProjectile.java
src/main/java/com/hollingsworth/arsnouveau/setup/ItemsRegistry.java
src/main/resources/assets/ars_nouveau/blockstates/scryers_oculus.json
src/main/resources/data/ars_nouveau/tags/blocks/golem/budding.json
src/main/resources/data/ars_nouveau/tags/blocks/golem/cluster.json
src/main/resources/data/ars_nouveau/tags/items/golem/shard.json

Backported tag behavior for the golem.
Fix turret behavior of Mageblock.
Fix oculus blockstate error.
Backported creative spell tier #583
Backported Source Jar cutout #617
Added a height ratio offset for splits #556

Backports of golem, jar and creative tier

---

src/main/java/com/hollingsworth/arsnouveau/ArsNouveau.java
src/main/java/com/hollingsworth/arsnouveau/api/mana/ManaAttributes.java
src/main/java/com/hollingsworth/arsnouveau/api/util/ManaUtil.java

Added the Attributes max_mana and mana_regen
they'll just be added ontop of the return value in the getMaxMana and getManaRegen

Added Mana Attributes for 1.18

---

src/main/java/com/hollingsworth/arsnouveau/client/ClientHandler.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectCrush.java
src/main/resources/assets/ars_nouveau/lang/en_us.json

Crush backport from Elemental

---

src/main/java/com/hollingsworth/arsnouveau/api/client/IVariantColorProvider.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/EntityBookwyrm.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/EntityDrygmy.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/EntityWixie.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/Whirlisprig.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectHarm.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectWindshear.java

Also allowing Harm & WS to hit the ender dragon again.

Color getters for Identity patch

---

src/main/java/com/hollingsworth/arsnouveau/api/spell/AbstractFilter.java
src/main/java/com/hollingsworth/arsnouveau/api/spell/IFilter.java
src/main/java/com/hollingsworth/arsnouveau/common/datagen/PatchouliProvider.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/goal/carbuncle/GoToPosGoal.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectConjureWater.java
src/main/resources/data/ars_nouveau/patchouli_books/worn_notebook/en_us/entries/resources/decorative.json

Access modifier on GoToPosGoal.
Extended ConjureWater to fill Botania Apothecaries and simila that implement LiquidBlockContainer.
Restored sourcestone recipe page.

Common interface for Filters. Sourcestone recipe page and misc.

---

src/main/java/com/hollingsworth/arsnouveau/common/block/LightBlock.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectLight.java

Implements the necessary code on the block class, and adds a fluid check on placement in the effect class.

Allow summoned lights to be waterlogged

---

src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/AlterationTableRenderer.java
src/main/java/com/hollingsworth/arsnouveau/common/block/tile/AlterationTile.java

https://user-images.githubusercontent.com/5553605/189511956-f9cdad5f-e91a-4186-840f-45b3005d5168.mp4

add a little animation to the alteration table

---

src/main/java/com/hollingsworth/arsnouveau/ArsNouveau.java
src/main/java/com/hollingsworth/arsnouveau/api/ritual/DispenserRitualBehavior.java
src/main/java/com/hollingsworth/arsnouveau/client/events/ClientHandler.java
src/main/java/com/hollingsworth/arsnouveau/client/renderer/entity/DummyRenderer.java
src/main/java/com/hollingsworth/arsnouveau/common/armor/AnimatedMagicArmor.java
src/main/java/com/hollingsworth/arsnouveau/common/block/RitualBrazierBlock.java
src/main/java/com/hollingsworth/arsnouveau/common/block/TempLightBlock.java
src/main/java/com/hollingsworth/arsnouveau/common/block/tile/LightTile.java
src/main/java/com/hollingsworth/arsnouveau/common/block/tile/TempLightTile.java
src/main/java/com/hollingsworth/arsnouveau/common/datagen/PatchouliProvider.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/EntityDummy.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/EntityProjectileSpell.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/SummonSkeleton.java
src/main/java/com/hollingsworth/arsnouveau/common/event/EventHandler.java
src/main/java/com/hollingsworth/arsnouveau/common/lib/LibBlockNames.java
src/main/java/com/hollingsworth/arsnouveau/common/light/LightManager.java
src/main/java/com/hollingsworth/arsnouveau/common/perk/ChillingPerk.java
src/main/java/com/hollingsworth/arsnouveau/common/perk/IgnitePerk.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectBlink.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectCut.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectExchange.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectLight.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/method/MethodProjectile.java
src/main/java/com/hollingsworth/arsnouveau/setup/BlockRegistry.java
src/main/java/com/hollingsworth/arsnouveau/setup/Config.java
src/main/resources/ars_nouveau.mixins.json
src/main/resources/assets/ars_nouveau/blockstates/temporary_light_block.json
src/main/resources/assets/ars_nouveau/lang/en_us.json
src/main/resources/data/ars_nouveau/patchouli_books/worn_notebook/en_us/entries/armor/armor_upgrade.json

Teleport Events for spells.
Fix self-thread effects.
Elytra mixin in the client block.#703
Fixing the Slim Dummy. #526
Temporary Lights. #527
Time config for spell projectile lifespan. #550
Increasing Skellies range. #638
Adding froglights to dyn lights. #678
Using InventoryHelper to give the notebook, so it's not an item entity that can spawn elsewhere. #682

Bunch of fix and to-do features.

---

build.gradle
src/main/java/com/hollingsworth/arsnouveau/common/world/biome/ModBiomes.java

Conflict on redwood ticket since byg and archwood forest's fern/forest flowers were inverted (vanilla have no standard for this combo)

Hotfix byg feature cycle

---

src/main/resources/assets/ars_nouveau/lang/uk_ua.json

Uk ua localisation update

---

src/main/java/com/hollingsworth/arsnouveau/common/block/RotatingSpellTurret.java
src/main/java/com/hollingsworth/arsnouveau/common/block/tile/RotatingTurretTile.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/EntityProjectileSpell.java
src/main/java/com/hollingsworth/arsnouveau/common/items/SpellBow.java
src/main/java/com/hollingsworth/arsnouveau/common/items/SpellCrossbow.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectKnockback.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectLaunch.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectLeap.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/method/MethodProjectile.java

Also moved adjustable turrets logic to a separate map

Split Rework, Leap blockbending

---

src/main/java/com/hollingsworth/arsnouveau/common/entity/WealdWalker.java

this fixes compatibility with Quark where they implement a Foxhound, a tameable enemy

fix: prevent weald walkers from attacking tamed creatures

---

src/main/java/com/hollingsworth/arsnouveau/api/util/MathUtil.java
src/main/java/com/hollingsworth/arsnouveau/common/ritual/RitualMoonfall.java
src/main/java/com/hollingsworth/arsnouveau/common/ritual/RitualSunrise.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/augment/AugmentDampen.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectDelay.java

* Fix Delay and Duration modifiers behaving incorrectly
* Add a gradual time-set to Time ritual to make the sky/sun/moon cycle

Time of Fix of Time

---

src/main/java/com/hollingsworth/arsnouveau/common/block/ArchfruitPod.java

This should fix Create harvesters and other mechanics that interact with CocoaBlocks

fix: make archfruit inherit from CocoaBlock

---

src/main/java/com/hollingsworth/arsnouveau/common/datagen/LangDatagen.java

No longer existing Glyphs should be used in docs ;)

Removed Strength from mirror documentation

---

src/main/java/com/hollingsworth/arsnouveau/api/event/SpellProjectileHitEvent.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/EntityProjectileSpell.java

so that addons can do things when spell projectiles hit

add spell projectile hit event

---

src/main/java/com/hollingsworth/arsnouveau/api/spell/SpellResolver.java

this is a very small but rather important change to make addons work correctly.

fix discounts from spells not applying

---

src/main/java/com/hollingsworth/arsnouveau/api/event/SpellProjectileHitEvent.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/EntityProjectileSpell.java

See #1083 for the original 1.20 PR.

Backport spell projectile event to 1.19

---

src/generated/resources/.cache/fcc0d197db45e404a8bc894ca09c0611e5a65cab
src/generated/resources/data/ars_nouveau/tags/entity_types/jar_whitelist.json
src/main/java/com/hollingsworth/arsnouveau/api/event/DelayedSpellEvent.java
src/main/java/com/hollingsworth/arsnouveau/common/block/MobJar.java
src/main/java/com/hollingsworth/arsnouveau/common/datagen/EntityTagProvider.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectBreak.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectConjureWater.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectCrush.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectDelay.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectEnderChest.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectEvaporate.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectFell.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectFirework.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectGravity.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectGrow.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectHarvest.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectIgnite.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectIntangible.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectInvisibility.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectLeap.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectLight.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectPhantomBlock.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectRedstone.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectRune.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectSenseMagic.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectSlowfall.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectSmelt.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectSnare.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectToss.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectWither.java

- [Move delay to last position of dead mob instead of interrupting](https://github.com/baileyholl/Ars-Nouveau/commit/ece24b991ded65e5b28ea2e0671f38ffc95162fc)
- [Make Mining Fatigue reduce mining level](https://github.com/baileyholl/Ars-Nouveau/commit/4c3e53864ea7e6ab9f58bdc4997cdefb2814056c)
- [Config to Nerf Leap to only work while on ground](https://github.com/baileyholl/Ars-Nouveau/commit/879e209afbd8689ed4e8577b20a453fd4ee379b3)
- [Smelt on items RecipeSwap](https://github.com/baileyholl/Ars-Nouveau/commit/3ad2b9bff7a360e5b534f61056b087efed3fd5e7)

A bunch of requested features

---

src/generated/resources/.cache/09052f72ebaca818ff2331d4b38a7dfd4768ffe4
src/generated/resources/data/ars_nouveau/tags/mob_effect/deny_dispel.json
src/main/java/com/hollingsworth/arsnouveau/common/datagen/PotionEffectTagProvider.java
src/main/java/com/hollingsworth/arsnouveau/common/lib/PotionEffectTags.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectDispel.java

Mob effect tags to allow or disallow the use of Dispel to remove them

Dispel tags

---

src/main/java/com/hollingsworth/arsnouveau/api/spell/AbstractFilter.java
src/main/java/com/hollingsworth/arsnouveau/api/spell/IFilter.java
src/main/java/com/hollingsworth/arsnouveau/common/block/RuneBlock.java

so that block filters can actually check the block they're supposed to filter

add world to IFilter

---

src/main/java/com/hollingsworth/arsnouveau/client/gui/book/InfinityGuiSpellBook.java
src/main/java/com/hollingsworth/arsnouveau/client/gui/buttons/InfinityCraftingButton.java
src/main/java/com/hollingsworth/arsnouveau/common/items/SpellBook.java
src/main/java/com/hollingsworth/arsnouveau/common/network/PacketOpenSpellBook.java
src/main/java/com/hollingsworth/arsnouveau/setup/config/ServerConfig.java

InfinityGui is only used when the config is true, so it doesn't risk bugs leaking into classic plays

Squashed InfinitySpells and moved to alt classes

---

src/main/java/com/hollingsworth/arsnouveau/common/potions/FlightEffect.java

Currently, if you have the flight effect applied, and another instance of the effect is applied, you drop out of flight.
This may only affect other mods that provide a way to acquire the flight effect.
1. `/effect give @p ars_nouveau:flight 60`
2. Start flying, and run the command again. You will drop out of flight, but can still fly.
This happens because `LivingEntity::onEffectUpdated` also calls `removeAttributeModifiers`. 
`onEffectTick` refreshes `mayfly` the next tick, but `flying` is already set to false. 
Unlike `LivingEntity::removeEffect` which is called when the effect expires, the MobEffectInstance is still present at this point.
Adding a check for flight duration to `removeAttributeModifiers` fixes this for updates.
1. Rerun the first set of tests. With this fix you no longer …

Set attribute modifiers for flight effect when duration changes

---

src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectBurst.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectLinger.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectRune.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectWall.java

stop original spell, reset callback will counter-cancel and handle the remainder

Reset fixes

---

src/main/java/com/hollingsworth/arsnouveau/common/light/DynamLightUtil.java

Dynlight for player armors

---

src/main/java/com/hollingsworth/arsnouveau/setup/registry/ItemsRegistry.java

Make wilden tribute immune to fire so that magefire doesn't destroy it when the loot drops

feat: make wilden tribute fire resistant

---

supporters.json

It's even correct in the discord message! :P
[Source](https://discord.com/channels/743298050222587978/1116864417724895373/1118066396908224603)

Fix typo in my starby name

---

src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectKnockback.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectLeap.java

Knockback and leap fix on turrets

Look angle fix 1.21 

---

build.gradle
src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/ImbuementRenderer.java
src/main/java/com/hollingsworth/arsnouveau/common/block/tile/ImbuementTile.java

also added example localRuntime swap from runTimeOnly

swap IER with direct item entity in imbuement chamber. 

---

src/main/java/com/hollingsworth/arsnouveau/client/gui/SchoolTooltip.java
src/main/java/com/hollingsworth/arsnouveau/client/jei/JEIArsNouveauPlugin.java
src/main/java/com/hollingsworth/arsnouveau/common/items/Glyph.java

Adds jei aliases for glyph items (lost due to hiding school while shifting)

hotfix on positioning, aliases for school 

---

src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/AlterationTableRenderer.java

Thanks to Chonky for helping get the rendering up and running

feat: parameterised tier display for Alteration Table

---

build.gradle
src/main/java/com/hollingsworth/arsnouveau/client/container/AbstractStorageTerminalScreen.java
src/main/java/com/hollingsworth/arsnouveau/client/container/CraftingTerminalMenu.java
src/main/java/com/hollingsworth/arsnouveau/client/container/StorageTerminalMenu.java
src/main/java/com/hollingsworth/arsnouveau/common/block/CraftingLecternBlock.java
src/main/java/com/hollingsworth/arsnouveau/common/block/tile/CraftingLecternTile.java
src/main/java/com/hollingsworth/arsnouveau/common/block/tile/StorageLecternTile.java
src/main/java/com/hollingsworth/arsnouveau/common/network/ClientToServerStoragePacket.java
src/main/java/com/hollingsworth/arsnouveau/common/network/SetTerminalSettingsPacket.java

Rewrote search functionality:
- Item tag search
- Item component search
- Mod search
- Tooltip search
- No sync search
- No sync crafting table

feat: add player based storage lectern operations

---

src/main/java/com/hollingsworth/arsnouveau/api/spell/SpellContext.java
src/main/java/com/hollingsworth/arsnouveau/api/spell/wrapped_caster/RuneCaster.java
src/main/java/com/hollingsworth/arsnouveau/common/block/tile/RuneTile.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/EntityProjectileSpell.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectBlink.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectExchange.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectPickup.java

fixed glyphs are blink, pickup, and exchange, there's probably a few more issues to resolve and a few more completely broken glyphs though.

fix: make some glyphs (partially) work x-dim, x-dim runes, spell proj dim changes

---

src/main/java/com/hollingsworth/arsnouveau/api/spell/SpellResolver.java

there are a lot of ways to fix this issue, but i like this one the most

fix: touch turrets take double source

---

src/main/java/com/hollingsworth/arsnouveau/common/items/SpellBook.java

should remove the impact of latency if you switch to a spell then edit it

fix: set slot on client after radial selection

---

src/generated/resources/data/ars_nouveau/tags/entity_type/vitalic_death_blacklist.json
src/generated/resources/data/ars_nouveau/tags/entity_type/vitalic_growth_blacklist.json
src/main/java/com/hollingsworth/arsnouveau/common/block/tile/VitalicSourcelinkTile.java
src/main/java/com/hollingsworth/arsnouveau/common/datagen/EntityTagProvider.java
src/main/java/com/hollingsworth/arsnouveau/common/lib/EntityTags.java

makes it consistent with Ritual of Overgrowth

feat: make vitalic sourcelink work on AgeableMob instead of just Animal

---

src/main/java/com/hollingsworth/arsnouveau/common/mixin/BlockItemAccessor.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectExchange.java
src/main/resources/ars_nouveau.mixins.json

https://canary.discord.com/channels/743298050222587978/1338359057404264458

fix: exchange not respecting components

---

src/main/java/com/hollingsworth/arsnouveau/common/entity/pathfinding/pathjobs/AbstractPathJob.java

fix starby pathfinding 1.19.x

---

src/main/java/com/hollingsworth/arsnouveau/client/gui/book/GuiSpellBook.java

allows splitting spell into any empty space after the clicked cell and validates spell after split

feat: better spell splitting

---

src/main/java/com/hollingsworth/arsnouveau/client/emi/EmiArsNouveauPlugin.java
src/main/java/com/hollingsworth/arsnouveau/client/emi/EmiLecternRecipeHandler.java

shift clicking doesnt work but i dont think it worked with the jei handler that this one is based off of anyway.

feat: emi recipe handler for lectern

---

src/generated/resources/data/ars_nouveau/advancement/recipes/misc/bastion_to_purple.json
src/generated/resources/data/ars_nouveau/advancement/recipes/misc/bombegranate_to_orange.json
src/generated/resources/data/ars_nouveau/advancement/recipes/misc/frostaya_to_light_blue.json
src/generated/resources/data/ars_nouveau/advancement/recipes/misc/mendosteen_to_lime.json
src/generated/resources/data/ars_nouveau/recipe/bastion_to_purple.json
src/generated/resources/data/ars_nouveau/recipe/bombegranate_to_orange.json
src/generated/resources/data/ars_nouveau/recipe/frostaya_to_light_blue.json
src/generated/resources/data/ars_nouveau/recipe/mendosteen_to_lime.json
src/main/java/com/hollingsworth/arsnouveau/common/datagen/RecipeDatagen.java

https://canary.discord.com/channels/743298050222587978/1337421585153527818

feat: archfruit to dye recipes

---

src/generated/resources/assets/ars_nouveau/lang/en_us.json
src/main/java/com/hollingsworth/arsnouveau/common/block/tile/RedstoneRelayTile.java
src/main/java/com/hollingsworth/arsnouveau/common/datagen/LangDatagen.java

update more blocks when power changed, move current power to lang

feat: redstone relay tweaks

---

src/main/java/com/hollingsworth/arsnouveau/common/perk/RepairingPerk.java
src/main/java/com/hollingsworth/arsnouveau/setup/config/Config.java

https://canary.discord.com/channels/743298050222587978/1344071927903289486

feat: add config for base armor repair rate

---

src/generated/resources/assets/ars_nouveau/lang/en_us.json
src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectInteract.java

feat: dampen to interact with shift

---

src/main/java/com/hollingsworth/arsnouveau/client/container/AbstractStorageTerminalScreen.java
src/main/java/com/hollingsworth/arsnouveau/client/container/CraftingTerminalMenu.java
src/main/java/com/hollingsworth/arsnouveau/client/container/StorageTerminalMenu.java
src/main/java/com/hollingsworth/arsnouveau/client/emi/EmiLecternRecipeHandler.java
src/main/java/com/hollingsworth/arsnouveau/client/jei/CraftingTerminalTransferHandler.java
src/main/java/com/hollingsworth/arsnouveau/common/network/ClientToServerStoragePacket.java

raw nbt tag manipulation is confusing at best

feat: use stream codecs for ClientToServerStoragePacket

---

src/main/java/com/hollingsworth/arsnouveau/common/block/tile/CraftingLecternTile.java

because im used to ae2's behavior

feat: prefer stacks in player inventory to stored stacks when filling from recipe

---

src/generated/resources/data/ars_nouveau/tags/block/an_decorative.json
src/generated/resources/data/ars_nouveau/tags/block/an_false_occlusion.json
src/main/java/com/hollingsworth/arsnouveau/api/event/InvalidateMirrorweaveRender.java
src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/FalseweaveRenderer.java
src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/GhostweaveRenderer.java
src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/MirrorweaveRenderer.java
src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/SkyBlockRenderer.java
src/main/java/com/hollingsworth/arsnouveau/common/block/GhostWeave.java
src/main/java/com/hollingsworth/arsnouveau/common/block/MirrorWeave.java
src/main/java/com/hollingsworth/arsnouveau/common/block/SkyWeave.java
src/main/java/com/hollingsworth/arsnouveau/common/block/tile/MirrorWeaveTile.java
src/main/java/com/hollingsworth/arsnouveau/common/block/tile/SkyBlockTile.java
src/main/java/com/hollingsworth/arsnouveau/common/datagen/BlockTagProvider.java
src/main/java/com/hollingsworth/arsnouveau/setup/registry/BlockRegistry.java
src/main/resources/META-INF/accesstransformer.cfg

Resolves [#1221](https://github.com/baileyholl/Ars-Nouveau/issues/1221)

perf: mirrorweave rendering #1221

---

src/generated/resources/assets/ars_nouveau/lang/en_us.json
src/main/java/com/hollingsworth/arsnouveau/api/ritual/AbstractRitual.java
src/main/java/com/hollingsworth/arsnouveau/common/block/tile/RitualBrazierTile.java
src/main/java/com/hollingsworth/arsnouveau/common/datagen/LangDatagen.java
src/main/java/com/hollingsworth/arsnouveau/common/ritual/RitualBreed.java

mainly for extra conditions (fertility's < 20 animal rule) and addons

feat: ritual specific tooltips

---

src/main/java/com/hollingsworth/arsnouveau/client/emi/EmiApparatusEnchantingRecipe.java

https://canary.discord.com/channels/743298050222587978/1354254022907007027

fix: only init EMI reactive enchantable list once

---

src/generated/resources/data/ars_nouveau/tags/entity_type/bubble_blacklist.json
src/main/java/com/hollingsworth/arsnouveau/ArsNouveau.java
src/main/java/com/hollingsworth/arsnouveau/api/event/EntityPreRemovalEvent.java
src/main/java/com/hollingsworth/arsnouveau/common/datagen/EntityTagProvider.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/BubbleEntity.java
src/main/java/com/hollingsworth/arsnouveau/common/lib/EntityTags.java
src/main/java/com/hollingsworth/arsnouveau/common/mixin/EntityMixin.java

add blacklist tag and pop bubbles if rider is removed
blacklist includes projectiles not affected by gravity and ars helper mobs by default

feat: bubble tweaks

---

src/main/java/com/hollingsworth/arsnouveau/common/entity/statemachine/starbuncle/DepositItemState.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/statemachine/starbuncle/TakeItemState.java

this check makes starbies unable to use composters

fix: make starbies ignore absence of tile

---

src/generated/resources/data/c/tags/item/tools/fishing_rod.json
src/generated/resources/data/c/tags/item/tools/mining_tool.json
src/generated/resources/data/minecraft/tags/item/enchantable/mining.json
src/generated/resources/data/minecraft/tags/item/enchantable/mining_loot.json
src/main/java/com/hollingsworth/arsnouveau/common/datagen/ItemTagProvider.java
src/main/java/com/hollingsworth/arsnouveau/common/items/EnchantersFishingRod.java
src/main/java/com/hollingsworth/arsnouveau/common/items/EnchantersGauntlet.java

Should theorically add the "multitool functionality" too. No idea on how it interacts with tiered harvestability tho.

Fix enchantability on new enchanter's items

---

src/main/java/com/hollingsworth/arsnouveau/client/renderer/entity/StarbuncleModel.java
src/main/java/com/hollingsworth/arsnouveau/common/entity/Starbuncle.java
src/main/resources/assets/ars_nouveau/geo/bootybuncle.geo.json

Fixes the conflict between the resting controller and the party controller, allowing the starby to shake its tail again.
Also bundles a named buncle with larger tail

Bootybuncle fix

---

src/main/java/com/hollingsworth/arsnouveau/client/container/AbstractStorageTerminalScreen.java
src/main/java/com/hollingsworth/arsnouveau/client/container/CraftingTerminalScreen.java

copies over new spellbook search logic

feat: lectern search improvements

---

src/main/java/com/hollingsworth/arsnouveau/client/gui/NoShadowTextField.java
src/main/java/com/hollingsworth/arsnouveau/client/gui/book/GuiSpellBook.java

pass unused key presses to search bar and make NoShadowTextField render selections

feat: spellbook ui improvements

---

src/main/java/com/hollingsworth/arsnouveau/client/container/AbstractStorageTerminalScreen.java

my last pr screwed it up for non-textual keys

fix: lectern search

---

src/main/java/com/hollingsworth/arsnouveau/common/items/SpellCrossbow.java

https://canary.discord.com/channels/743298050222587978/1367619894862024785

fix: spell crossbow loads even without enough mana

---

src/generated/resources/assets/ars_nouveau/lang/en_us.json
src/main/java/com/hollingsworth/arsnouveau/api/event/EventQueue.java
src/main/java/com/hollingsworth/arsnouveau/api/perk/PerkAttributes.java
src/main/java/com/hollingsworth/arsnouveau/common/datagen/LangDatagen.java
src/main/java/com/hollingsworth/arsnouveau/common/event/timed/RewindEvent.java
src/main/java/com/hollingsworth/arsnouveau/common/mixin/EntityMixin.java
src/main/java/com/hollingsworth/arsnouveau/common/mixin/LivingEntityMixin.java
src/main/java/com/hollingsworth/arsnouveau/common/spell/rewind/RewindEntityData.java
src/main/resources/ars_nouveau.mixins.json

fix: #1798 rewind not setting gravity to false on log out

---

src/main/java/com/hollingsworth/arsnouveau/client/emi/EmiAlakarkinosRecipe.java
src/main/java/com/hollingsworth/arsnouveau/client/emi/EmiApparatusEnchantingRecipe.java
src/main/java/com/hollingsworth/arsnouveau/client/emi/EmiArmorUpgradeRecipe.java
src/main/java/com/hollingsworth/arsnouveau/client/emi/EmiEnchantingApparatusRecipe.java
src/main/java/com/hollingsworth/arsnouveau/client/emi/EmiImbuementRecipe.java
src/main/java/com/hollingsworth/arsnouveau/client/emi/EmiMultiInputRecipe.java
src/main/java/com/hollingsworth/arsnouveau/client/events/ClientEvents.java
src/main/java/com/hollingsworth/arsnouveau/common/event/EventHandler.java

perf: cache expensive generation of inputs and outputs for EMI

---

src/main/java/com/hollingsworth/arsnouveau/ArsNouveau.java
src/main/java/com/hollingsworth/arsnouveau/api/ArsNouveauAPI.java
src/main/java/com/hollingsworth/arsnouveau/api/registry/AlakarkinosConversionRegistry.java
src/main/java/com/hollingsworth/arsnouveau/common/event/EventHandler.java

fix: loading karky recipes on server start and reloading afterwards
