src/main/java/com/hollingsworth/arsnouveau/common/block/ArcaneOre.java, src/main/resources/data/ars_nouveau/loot_tables/blocks/arcane_ore.json, src/main/resources/data/forge/tags/blocks/ores/mana_gem.json, src/main/resources/data/forge/tags/items/gems.json, src/main/resources/data/forge/tags/items/gems/mana_gem.json, src/main/resources/data/forge/tags/items/ores.json, src/main/resources/data/forge/tags/items/ores/mana_gem.json, src/main/resources/data/minecraft/tags/items/beacon_payment_items.json
Arcane ore:
- extends OreBlock instead of ModBlock
- adds Forge tags for classification
- respects Silk Touch and Fortune effects
- drops XP comparable to lapis or redstone if broken without Silk Touch
Mana gem:
- adds Forge tags for classification
- may be used as payment to reconfigure a beacon
=> Make arcane ore and mana gem slightly better citizens.

build.gradle, src/main/java/com/hollingsworth/arsnouveau/common/compat/crafttweaker/EnchantingApparatusManager.java, src/main/java/com/hollingsworth/arsnouveau/common/compat/crafttweaker/GlyphPressManager.java
Docs will be PR'd to the CraftTweaker Docs repo, and will be hosted on https://docs.blamejared.com
This is the script I used to test it, it should cover everything that can be done in JSON with it
Also I put CraftTweaker has a compileOnly because we don't really have an :api and I don't think you guys really want waste the CPU cycles loading more mods when deving, happy to change it though
```zenscript
<recipetype:ars_nouveau:glyph_recipe>.removeRecipe(<item:ars_nouveau:glyph_touch>);
<recipetype:ars_nouveau:glyph_recipe>.addRecipe("glyph_test", "one", <item:minecraft:dirt>, <item:minecraft:diamond>);
<recipetype:ars_nouveau:enchanting_apparatus>.removeRecipe(<item:ars_nouveau:ring_of_lesser_discount>);
<recipetype:ars_nouveau:enchanting_apparatus>.addRecipe("enchanting_test", …
```
=> Add CraftTweaker support

src/main/java/com/hollingsworth/arsnouveau/api/util/SpellUtil.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectBreak.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectCrush.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectCut.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectFell.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectGrow.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectHarvest.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectIgnite.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectSmelt.java
- For multiple block-affecting effects that accept AOE to expand parallel to the struck surface, pierce expands deeper into the struck surface.
- Fell no longer performs initial AOE expansion, since it self-expands by tracing connected fellable blocks.
=> AOE and pierce refinements

src/main/resources/data/ars_nouveau/patchouli_books/worn_notebook/en_us/entries/apparatus/sylph_charm.json, src/main/resources/data/ars_nouveau/patchouli_books/worn_notebook/ko_kr/entries/apparatus/sylph_charm.json, src/main/resources/data/ars_nouveau/recipes/allow_scroll.json
While using mods such as Quark that added their own chests/remove vanilla chest crafting, crafting of void jar becomes impossible. This should fix this by checking for forge:chest instead of minecraft:chest. Also adds the same functionality to sylph charm multiblock.
=> Change minecraft:chest to forge:chest

src/main/java/com/hollingsworth/arsnouveau/common/items/SpellBook.java
This small change just adds a constructor that allows new types of spellbooks to change from the default renderer without interfering with existing functionality c:
=> Add Constructor without predetermined Properties

src/main/java/com/hollingsworth/arsnouveau/setup/Config.java
Changing this line'll default to true whenever a glyph is added by an addon that *isn't* in the default Config, preventing an NPE crash for addons that add new glpyhs and spell parts.
=> Default to true if a spellPart isn't found

src/main/java/com/hollingsworth/arsnouveau/api/ArsNouveauAPI.java, src/main/java/com/hollingsworth/arsnouveau/api/spell/AbstractCastMethod.java, src/main/java/com/hollingsworth/arsnouveau/api/spell/AbstractEffect.java, src/main/java/com/hollingsworth/arsnouveau/api/spell/AbstractSpellPart.java, src/main/java/com/hollingsworth/arsnouveau/api/spell/ISpellValidator.java, src/main/java/com/hollingsworth/arsnouveau/api/spell/SpellResolver.java, src/main/java/com/hollingsworth/arsnouveau/api/spell/SpellValidationError.java, src/main/java/com/hollingsworth/arsnouveau/client/gui/ModdedScreen.java, src/main/java/com/hollingsworth/arsnouveau/client/gui/book/GuiSpellBook.java, src/main/java/com/hollingsworth/arsnouveau/client/gui/buttons/CraftingButton.java, src/main/java/com/hollingsworth/arsnouveau/client/gui/buttons/CreateSpellButton.java, src/main/java/com/hollingsworth/arsnouveau/client/gui/buttons/GlyphButton.java, src/main/java/com/hollingsworth/arsnouveau/client/gui/buttons/GuiImageButton.java, src/main/java/com/hollingsworth/arsnouveau/client/gui/buttons/GuiSpellSlot.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/validation/AbstractSpellValidator.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/validation/ActionAugmentationPolicyValidator.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/validation/BaseSpellValidationError.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/validation/CombinedSpellValidator.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/validation/GlyphMaxTierValidator.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/validation/GlyphOccurrencesPolicyValidator.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/validation/MaxOneCastMethodSpellValidator.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/validation/NonEmptySpellValidator.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/validation/ScanningSpellValidator.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/validation/SpellPhraseValidator.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/validation/StandardSpellValidator.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/validation/StartingCastMethodSpellValidator.java, src/main/java/com/hollingsworth/arsnouveau/common/util/SpellPartConfigUtil.java, src/main/java/com/hollingsworth/arsnouveau/setup/Config.java, src/main/resources/assets/ars_nouveau/lang/en_us.json
Added validation system for spells
Always Active:
- Maximum one cast method (Form) per spell
- Enforce configuration for the maximum number of times a given glyph map appear
- Enforce configuration for the maximum number of times an given augment may be applied to a form or effect
Casting Time Only:
- Spell must not be empty
- Spell must start with a form glyph
Bonuses:
- Fixed a number of bugs in the Spell Book UI
- Now showing Glyphs that are a higher tier than the book but were learned anyway (You still can't add them to a spell)
Implements https://github.com/baileyholl/Ars-Nouveau/issues/242
=> Implemented validation and glyph count limitations

src/main/java/com/hollingsworth/arsnouveau/api/item/ICasterTool.java, src/main/java/com/hollingsworth/arsnouveau/api/spell/SpellResolver.java, src/main/java/com/hollingsworth/arsnouveau/common/items/EnchantersSword.java, src/main/java/com/hollingsworth/arsnouveau/common/items/SpellBow.java, src/main/java/com/hollingsworth/arsnouveau/common/items/Wand.java, src/main/java/com/hollingsworth/arsnouveau/common/network/Networking.java, src/main/java/com/hollingsworth/arsnouveau/common/network/PacketNoSpamChatMessage.java, src/main/java/com/hollingsworth/arsnouveau/common/util/PortUtil.java, src/main/resources/META-INF/accesstransformer.cfg
* New Packet: PacketNoSpamChatMessage
* When a client receives this packet, it will first delete any existing message with a matching id then display the contained message.
* Converted SpellResolver and all ICasterItems to use the no-spam messaging.
Note: **Access transformers were changed!** Developers may need to refresh their gradle project.
=> Reduced spam around spell casting and inscribing spells onto items

src/main/java/com/hollingsworth/arsnouveau/common/block/SconceBlock.java
Instead, we block the placement outright
Alternative fix:
```java
// Fall back on player facing.
return this.defaultBlockState().setValue(FACING, context.getHorizontalDirection().getOpposite());
```
=> SconceBlock: Fixed crashing when trying to place a sconce on the floor or ceiling

src/main/java/com/hollingsworth/arsnouveau/common/block/tile/ArcanePedestalTile.java, src/main/java/com/hollingsworth/arsnouveau/common/block/tile/CrystallizerTile.java, src/main/java/com/hollingsworth/arsnouveau/common/block/tile/EnchantingApparatusTile.java, src/main/java/com/hollingsworth/arsnouveau/common/block/tile/GlyphPressTile.java
Added the IItemHandler capability to the following blocks:
* Crystallizer
* Arcane Pedestal
* Enchanting Apparatus
* Glyph Press (Sided)
Fixes #204
=> Added the IItemHandler capability to a few blocks

src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectBounce.java
This attempts to address an issue regarding the newly added bounce effect being applied to spellcasters as opposed to the actual raytraced entity. Whether this was intentional or not is unknown to me, but if it was, feel free to ignore this, and apologies.
=> Fix Bounce effect being applied to caster

src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/ArcanePedestalRenderer.java, src/main/java/com/hollingsworth/arsnouveau/common/block/tile/ArcanePedestalTile.java
The entity rotation animation on the Arcane Pedestal moves too quickly or too slow depending on the framerate. These changes attempt to address the issue by introducing `getDeltaFrameTime()` from the Minecraft instance.
In the `tileEntityIn.frames` increment, a value of `1.5f` was chosen as the speed scalar, which if set to a value lower than 1, will determine the speed of the rotation, but may also appear choppy due to the actual rotation method needing to be casted to an int, I assume.
The increment I have set seems optimal enough, but if I have made an error or assumedly changed otherwise, I greatly apologize and am willing to re-edit based on input.
EDIT: Forgot to add a [demo video.](https://user-images.githubusercontent.com/9144208/132780987-c56e837f-f567-401a-a251-9092b1117807.mp4)
=> Fix pedestal rotation being independent from frametime

src/main/java/com/hollingsworth/arsnouveau/client/gui/book/GuiSpellBook.java
i noticed i edited & replaced spells a lot, would be nice of the clear button also erased the typed name, a bit of a QOL thing 🤔
=> Clear the spell's name when clear is pressed twice

src/main/java/com/hollingsworth/arsnouveau/api/ArsNouveauAPI.java, src/main/java/com/hollingsworth/arsnouveau/api/enchanting_apparatus/SpellWriteRecipe.java
-fixed the bug where all enchantments per enchanting apparatus were broken by reverting to the noncached Recipies for the enchanting apparatus (https://github.com/baileyholl/Ars-Nouveau/issues/398)
-fixed the bug were Writing the spell into an React item would fail by copying the way its inscribed Originaly
=> Bugfix:  React Enchantment.

src/main/java/com/hollingsworth/arsnouveau/client/gui/utils/RenderUtils.java
It's a little more transparent than the icon rendered ones, but I'm not sure if I can change that.
Might have been like that since I did ItemRender as well, I'm not sure anymore
=> Replaced Gl11 Function in ItemRendering with RenderSystem function

src/main/java/com/hollingsworth/arsnouveau/common/entity/SummonSkeleton.java
A summoned skeleton has a chance of dropping the weapon they are holding upon death. This can be potentially gamebreaking as other mods that have the ability to deconstruct the materials of tools can be exploited easily through this method.
I suppose it's a bit nitpicky to consider, as one would argue if someone would need it for something like netherite farming. Nevertheless, if it's an intended choice I do apologize for the confusion.
Take care.
=> Prevent summoned skeletons from dropping loot

src/main/java/com/hollingsworth/arsnouveau/common/entity/familiar/FamiliarEntity.java, src/main/java/com/hollingsworth/arsnouveau/common/entity/familiar/FamiliarStarbuncle.java, src/main/java/com/hollingsworth/arsnouveau/common/items/WixieHat.java
Make the Starbuncle familiar use the standard FamiliarData instead of the StarbuncleData that is way more complex now.
Fix Familiars duping their cosmetic items.
Wix the starby fam.
=> FamiliarData fix

src/main/resources/assets/ars_nouveau/lang/en_us.json
For the 1.18 branch the fixed translation is ars_nouveau.scryers_oculus.no_pos to ars_nouveau.scryers_eye.no_pos
=> Added and fixed translations

src/main/java/com/hollingsworth/arsnouveau/setup/BlockRegistry.java
The item is currently being created using ModBlockItem which overrides the default tooltip logic and prevents the tooltip defined in the block class from ever being appended. The simplest fix for this is to use BlockItem, as the potion jar was not using any of the methods added by ModBlockItem anyway.
=> Fix missing tooltip on potion jar item

src/main/java/com/hollingsworth/arsnouveau/client/ClientHandler.java, src/main/resources/assets/ars_nouveau/models/block/potion_jar/potion_jar10.json, src/main/resources/assets/ars_nouveau/models/block/potion_jar/potion_jar100.json, src/main/resources/assets/ars_nouveau/models/block/potion_jar/potion_jar20.json, src/main/resources/assets/ars_nouveau/models/block/potion_jar/potion_jar30.json, src/main/resources/assets/ars_nouveau/models/block/potion_jar/potion_jar40.json, src/main/resources/assets/ars_nouveau/models/block/potion_jar/potion_jar50.json, src/main/resources/assets/ars_nouveau/models/block/potion_jar/potion_jar60.json, src/main/resources/assets/ars_nouveau/models/block/potion_jar/potion_jar70.json, src/main/resources/assets/ars_nouveau/models/block/potion_jar/potion_jar80.json, src/main/resources/assets/ars_nouveau/models/block/potion_jar/potion_jar90.json, src/main/resources/assets/ars_nouveau/models/block/potion_jar/potion_jar_sliver.json, src/main/resources/assets/ars_nouveau/models/block/source_jar/source_jar10.json, src/main/resources/assets/ars_nouveau/models/block/source_jar/source_jar100.json, src/main/resources/assets/ars_nouveau/models/block/source_jar/source_jar20.json, src/main/resources/assets/ars_nouveau/models/block/source_jar/source_jar30.json, src/main/resources/assets/ars_nouveau/models/block/source_jar/source_jar40.json, src/main/resources/assets/ars_nouveau/models/block/source_jar/source_jar50.json, src/main/resources/assets/ars_nouveau/models/block/source_jar/source_jar60.json, src/main/resources/assets/ars_nouveau/models/block/source_jar/source_jar70.json, src/main/resources/assets/ars_nouveau/models/block/source_jar/source_jar80.json, src/main/resources/assets/ars_nouveau/models/block/source_jar/source_jar90.json, src/main/resources/assets/ars_nouveau/models/block/source_jar/source_jar_sliver.json, src/main/resources/assets/ars_nouveau/models/item/potion_jar.json, src/main/resources/assets/ars_nouveau/models/item/source_jar.json
Introduces two new item model properties for measuring the contents of source and potion jars. The item models have been expanded to include predicates for these properties, which determine the model to use based on the contents. The overrides delegate to the block models, and each previously unused block model has had a block/block parent defined in order to correct their transforms when rendered in item form. A color provider for the potion jar has also been added to ensure that the contents are displayed in the correct color.
=> Show amounts in source and potion jar models

src/main/java/com/hollingsworth/arsnouveau/common/items/Glyph.java
Changes the Glyph tooltip logic to check the actual Shift key rather than the sneak keybinding.
=> Check for Shift key instead of sneak keybinding in Glyph tooltip

build.gradle, src/main/java/com/hollingsworth/arsnouveau/client/renderer/entity/ModelLayerRenderer.java, src/main/java/com/hollingsworth/arsnouveau/common/potions/ModPotions.java, src/main/resources/META-INF/mods.toml
Since several modpacks need to move forward, I quickly fixed Ars Nouveau 1.16.5 to work with Geckolib 103.
Validated with people over at Roguelike Adventures and Dungeons 2
Would be great if you could release this.
=> Make it work with GeckoLib 103

src/main/java/com/hollingsworth/arsnouveau/ArsNouveau.java, src/main/java/com/hollingsworth/arsnouveau/api/spell/AbstractAugment.java, src/main/java/com/hollingsworth/arsnouveau/api/spell/AbstractCastMethod.java, src/main/java/com/hollingsworth/arsnouveau/api/spell/AbstractEffect.java, src/main/java/com/hollingsworth/arsnouveau/api/spell/AbstractSpellPart.java, src/main/java/com/hollingsworth/arsnouveau/client/gui/book/BaseBook.java, src/main/java/com/hollingsworth/arsnouveau/common/items/Glyph.java, src/main/resources/assets/ars_nouveau/lang/en_us.json, src/main/resources/pack.mcmeta
The item ordering of the creative tab will follow the book's.
Added an index in AbstractSpellPart to use for ordering instead of using hardcoded classification in COMPARE_GLYPH_BY_TYPE, allowing addons to give a specific order to their effects.
Default values:
1 for Methods
5 for Augments
10 for Effects
=> Split Creative Tab, making one just for Glyphs

build.gradle, src/main/java/com/hollingsworth/arsnouveau/client/waila/WailaArsNouveauPlugin.java
Behaviour explanation:
If in creative, spectator or have MAGIC_FIND_EFFECT, display blocks normally.
If block is ghostweave and it's invisible, display nothing.
If block is any type of mirror weave, display the mimic block.
=> feat: add WAILA plugin for mirrorweave blocks

src/main/java/com/hollingsworth/arsnouveau/api/spell/AbstractSpellPart.java, src/main/java/com/hollingsworth/arsnouveau/client/gui/book/GlyphUnlockMenu.java, src/main/java/com/hollingsworth/arsnouveau/client/gui/book/GuiSpellBook.java, src/main/java/com/hollingsworth/arsnouveau/setup/Config.java
This will hide disabled glyphs from being used inside the spellbook or shown in the unlock menu, it also enables the capability for glyphs to be implemented that aren't shown inside either of those places.
=> feat: create getters for displaying in spellbook and unlock menu

src/main/java/com/hollingsworth/arsnouveau/common/world/tree/MagicTrunkPlacer.java
This preserves the vanilla behaviour of only placing dirt under saplings
=> fix: only replace the sapling origin block with dirt

src/main/java/com/hollingsworth/arsnouveau/common/ritual/RitualMobCapture.java
Remove raiders from their active raid when capturing them
=> fix: remove pillagers in jars from raids

src/main/java/com/hollingsworth/arsnouveau/api/mob_jar/JarBehaviorRegistry.java
Fixes comparators not providing a signal when a mob jar behaviour hasn't been registered for the specific entity.
Falls back to call the method on the default mob jar behaviour when no specific behaviour has been registered.
=> fix: add default behavior dispatch fallback

src/main/java/com/hollingsworth/arsnouveau/common/event/JarEvents.java
This should fix the issues with the startRiding event, I checked loading in while in a boat, as well as loading the Nether, everything works as expected, may be worth doing some additional checks if you can think of anything before merge
=> fix: add entity checks to prevent mob jar riding crashing on Nether load

src/main/java/com/hollingsworth/arsnouveau/api/mob_jar/JarBehavior.java
Genericises the behaviour for interacting with an item instead of specific shears behaviour, this allows things like dyeing sheep in jars
=> feat: allow any item with entity interaction

src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/AgronomicRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/AlchemicalRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/AlterationTableRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/ArcaneCoreRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/ArsGeoBlockRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/BasicTurretRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/EnchantingApparatusRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/GenericRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/ImbuementRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/LecternRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/MycelialRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/PotionMelderRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/RepositoryRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/RotatingTurretRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/RuneRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/ScribesRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/ScryerEyeRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/VitalicRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/VolcanicRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/WhirlisprigFlowerRenderer.java
Adds `ArsGeoBlockRenderer` which translates the models by -0.01f, this fixes tile entities floating 0.1 pixels above the ground
=> fix: add ars geo renderer

src/main/java/com/hollingsworth/arsnouveau/api/enchanting_apparatus/EnchantingApparatusRecipe.java
Tested with and allows the following formats:
```json
{
"item": {
"item": "minecraft:crafting_table"
}
},
{
"item": "minecraft:diamond_axe"
},
[
{
"item": "minecraft:lightning_rod"
},
{
"item": "minecraft:stick"
}
]
```
=> fix: refactor to use stream with more guard statements

src/main/java/com/hollingsworth/arsnouveau/api/enchanting_apparatus/EnchantingApparatusRecipe.java, src/main/java/com/hollingsworth/arsnouveau/common/items/BlankParchmentItem.java
prevents spell parchment from being created without a valid spell
=> fix: validate parchment scribing (and fix compile issue, my bad)

src/main/java/com/hollingsworth/arsnouveau/common/ritual/RitualCloudshaper.java
Adds randomness to cloudshaper durations, sourced from 1.20 `WeatherCommand.java` source code
=> fix: add randomness to cloudshaper duration (1.19.x)

src/main/java/com/hollingsworth/arsnouveau/common/block/tile/BrazierRelayTile.java
fixes: #1111
relays can be linked to other relays. When linked in a loop the crash happens. This tracks the traversed relays in the inventory lookup performed by the harvest ritual and cancels the search when a loop is detected or when no inventory has been found after 255 block searches. I'm not sure if relay linking is intended, but if it's not, I'll remove that too
=> fixes recursivly looped inventory lookup in relays by keeping track of traversed relays

src/main/java/com/hollingsworth/arsnouveau/api/spell/AbstractEffect.java, src/main/java/com/hollingsworth/arsnouveau/api/spell/AbstractSpellPart.java, src/main/java/com/hollingsworth/arsnouveau/common/lib/GlyphLib.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectBurst.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectWall.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/validation/InvalidCombinationValidator.java, src/main/java/com/hollingsworth/arsnouveau/common/util/SpellPartConfigUtil.java
While this is potentially a breaking change, no known addons seems to use the invalid combinations field, so it might be possible to safely merge this on both 1.19.2 and 1.20
=> Invalid Combo configs

src/main/java/com/hollingsworth/arsnouveau/api/entity/ISummon.java, src/main/java/com/hollingsworth/arsnouveau/client/gui/utils/RenderUtils.java, src/main/java/com/hollingsworth/arsnouveau/common/entity/EntityAllyVex.java, src/main/java/com/hollingsworth/arsnouveau/common/items/curios/SummoningFocus.java, src/main/java/com/hollingsworth/arsnouveau/setup/config/Config.java
1) Add a config to disable the transparency stuff that crash with newer rubidium, as there is currently a split on mods that only support 0.6 and those that moved to support 0.7
2) Fix override methods in summoned vex having wrong signature and add an alternative getOwner to not clash with superclass as AllyVex use a private Owner field (as superclass uses Mob instead of LivingEntity)
=> Transparency cfg + Vex hotfixes

src/main/java/com/hollingsworth/arsnouveau/common/entity/EntityProjectileSpell.java
The pierce counter is reduced on bouncing, but is then reduced again on attemptRemoval (effectively wasting half pierces).
Moves pierce counter reduction to the isSensitive check, where attemptRemoval is not called.
=> Arc bounce hotfix

src/main/java/com/hollingsworth/arsnouveau/api/perk/IPerk.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/tile/AlterationTableRenderer.java, src/main/java/com/hollingsworth/arsnouveau/common/block/AlterationTable.java, src/main/java/com/hollingsworth/arsnouveau/common/block/tile/AlterationTile.java
Simply switches most of ArmorPerkHolder to StackPerkHolder for testing on threads for other item types, rendering of non-armor items have a weird offset to solve EDIT: Fixed
=> Alteration table for non-armors

src/main/java/com/hollingsworth/arsnouveau/common/mixin/DamageSourceMixin.java, src/main/resources/ars_nouveau.mixins.json
As requested in this thread https://discord.com/channels/743298050222587978/1224502026143137842
Will only display spell name if the spell is named, and will use the spells color, the hover shows the Spellbook they used but can be stripped out if desired.
=> feat: add spell name in death message

src/generated/resources/.cache/43f70b1d0fc3650d25dddf44c6efffef1900bb18, src/generated/resources/data/ars_nouveau/recipes/crush_glowstone_block_to_dust.json, src/main/java/com/hollingsworth/arsnouveau/client/jei/JEIConstants.java, src/main/java/com/hollingsworth/arsnouveau/common/datagen/CrushRecipeProvider.java
Adds a crush recipe to get the full 4 dusts from glowstone, fix the missing texture on crush recipes in jei
=> Fix that damn jei arrow + glowstone parity with quartz

src/main/java/com/hollingsworth/arsnouveau/client/renderer/item/SpellBookRenderer.java
This PR modifies the SpellBookRenderer to set up lighting state before getting the VertexConsumer from the BufferSource. This allows other mods to access the correct lighting state when creating a VertexConsumer for rendering the item.
The same PR has been opened in geckolib: https://github.com/bernie-g/geckolib/pull/584 but is needed here as well as the SpellBookRenderer overrides parts of the geckolib rendering code.
Helps to fix https://github.com/RaphiMC/ImmediatelyFast/issues/133
=> Set up lighting before getting VertexConsumer

src/main/java/com/hollingsworth/arsnouveau/api/util/LevelPosMap.java, src/main/java/com/hollingsworth/arsnouveau/common/mob_jar/WitherBehavior.java, src/main/java/com/hollingsworth/arsnouveau/setup/registry/APIRegistry.java
Adds Wither Jar behavior
- On redstone power it breaks a 3x3 area centered on the jar (needs to be powered through the blocks to break or via a spell)
- If a creature dies within 4 blocks of the jar, it produces a wither rose.
=> feat: add wither jar behavior

src/main/java/com/hollingsworth/arsnouveau/setup/config/ConfigUtil.java
for ids like  "everycomp:ch/ars_nouveau/archwood_torch=15" that failed otherwise
=> Allow regex to parse any char in the resourcelocation part of the string

src/main/java/com/hollingsworth/arsnouveau/client/jei/CraftingTerminalTransferHandler.java
Fix to allow matching items with empty tags, surface via a bug in Additions, but this seems to match what happens in other crafting terminals.
=> fix: allow storage lectern to match empty tags

src/main/java/com/hollingsworth/arsnouveau/api/event/EventQueue.java
1.21 adds /tick, which allows you to freeze the game. 
NeoForge will fire ServerTickEvent.Post regardless of whether the game is frozen. 
We also can not observe the effects of a one-tick tick step in ServerTickEvent.Post, so we need to hook into ServerTickEvent.Pre to find out if it was stepping.
=> fix: ignore frozen ticks in EventQueue

build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, src/main/java/com/hollingsworth/arsnouveau/api/item/ICosmeticItem.java, src/main/java/com/hollingsworth/arsnouveau/client/registry/ClientHandler.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/entity/StarbuncleModel.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/entity/StarbuncleRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/entity/WixieModel.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/entity/familiar/FamiliarBookwyrmRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/entity/familiar/FamiliarStarbyModel.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/entity/familiar/FamiliarWhirlisprigRenderer.java, src/main/java/com/hollingsworth/arsnouveau/client/renderer/entity/familiar/GenericFamiliarRenderer.java, src/main/java/com/hollingsworth/arsnouveau/common/entity/Starbuncle.java, src/main/java/com/hollingsworth/arsnouveau/common/entity/familiar/FamiliarEntity.java, src/main/java/com/hollingsworth/arsnouveau/common/entity/familiar/FamiliarJabberwog.java, src/main/java/com/hollingsworth/arsnouveau/common/entity/familiar/FamiliarStarbuncle.java, src/main/java/com/hollingsworth/arsnouveau/common/entity/familiar/FamiliarWhirlisprig.java, src/main/java/com/hollingsworth/arsnouveau/common/entity/familiar/FlyingFamiliarEntity.java, src/main/java/com/hollingsworth/arsnouveau/common/items/StarbuncleShades.java
Restores GenericFamiliarRenderer for rendering Cosmetic Accessories on all familiars that use it. (Amet golem currently not using it)
Make ICosmeticItem#getBone entity-sensitive to switch pivot based on entity for multiple support.
Allow hiding wixie hat if the familiar has an hat cosmetic. Allow Starbuncle Shades on all familiars.
=> Hats Off! Cosmetic system for familiars restored and upgraded

src/main/java/com/hollingsworth/arsnouveau/common/items/data/ItemScrollData.java
This PR fixes #1429 by changing `ItemScrollData.Mutable` from using `List#remove` for removing `ItemStacks` from the list, to using a manual iteration and comparing stacks using `ItemStack#isSameItem` (the same comparison method as `ItemScrollData#contains`).
As `ItemStack`s do not implement `Object#equals` properly, no two instances of an `ItemStack` will ever satisfy `Objects#equal` (in the default implementation from `Object`), even if their contents are identical since their identities are different. This is even more pronounced for `ItemScrollData.Mutable#remove`, which copies the stack before removing it; thus, it will _never_ match an existing stack in the list.
To work around this limitation, we now manually iterate the list and use `ItemStack#isSameItem`  (mirroring the same …
=> Fix item scroll data using List#remove for ItemStacks

src/main/java/com/hollingsworth/arsnouveau/common/command/DroplessMobsCommand.java, src/main/java/com/hollingsworth/arsnouveau/common/event/EventHandler.java, src/main/resources/META-INF/accesstransformer.cfg
The root command is quite cheap to run and thus does not require op, the "simulate" subcommand can get expensive and thus does require op.
This list of dropless mobs is useful for increasing the bonus in drygmy farms.
=> feat: command to list dropless mobs

src/main/java/com/hollingsworth/arsnouveau/api/event/DelayedSpellEvent.java
I am making an add-on for a mod pack I intent to create.
I made a spell that mines a  block over time, rather than breaking it instantly, but when mining a staircase into the ground it is annoying to always have the particles in your face, which is why I would be happy if they where optional.
=> Make particles of DelayedSpellEvent optional

src/main/java/com/hollingsworth/arsnouveau/client/gui/book/GuiSpellBook.java
A few additions/tweaks to spellbook controls:
- Auto focus search bar if charTyped returns false (shouldnt break search bar)
- Clear search bar on auto focus (manual focus wont clear)
- Add glyphs using number keys (previously incompatible w/ infinite spell demo)
- Swap glyphs using number keys (compatible w/ infinite spell demo)
- Split spell and add blank space with middle click
=> feat: spellbook control improvements

src/main/java/com/hollingsworth/arsnouveau/common/entity/Starbuncle.java
starby stacking breaks when done far from 0, 0 (presumably if not loaded)
also makes it so the new starby tries to ride the topmost starby or fails the interaction if it cant.
=> fix: starby stacking behaviour

src/main/java/com/hollingsworth/arsnouveau/api/util/PortalFrameTester.java
Fixes horizontal portals getting destroyed by block updates and horizontal portal generation. Horizontal portals will no longer break when receiving a block update. Horizontal portals can now be generated by throwing the scroll anywhere inside the frame and not just on the northernmost line of blocks.
=> Fix: Update PortalFrameTester.java (Closes #1063)

src/main/java/com/hollingsworth/arsnouveau/api/spell/wrapped_caster/TileCaster.java, src/main/java/com/hollingsworth/arsnouveau/api/util/SourceUtil.java, src/main/java/com/hollingsworth/arsnouveau/common/block/tile/BasicSpellTurretTile.java, src/main/java/com/hollingsworth/arsnouveau/common/block/tile/DrygmyTile.java, src/main/java/com/hollingsworth/arsnouveau/common/block/tile/EnchantingApparatusTile.java, src/main/java/com/hollingsworth/arsnouveau/common/block/tile/ImbuementTile.java, src/main/java/com/hollingsworth/arsnouveau/common/block/tile/PotionMelderTile.java, src/main/java/com/hollingsworth/arsnouveau/common/block/tile/RitualBrazierTile.java, src/main/java/com/hollingsworth/arsnouveau/common/block/tile/RotatingTurretTile.java, src/main/java/com/hollingsworth/arsnouveau/common/block/tile/RuneTile.java, src/main/java/com/hollingsworth/arsnouveau/common/block/tile/WhirlisprigTile.java, src/main/java/com/hollingsworth/arsnouveau/common/block/tile/WixieCauldronTile.java, src/main/java/com/hollingsworth/arsnouveau/common/entity/statemachine/alakarkinos/DecideCrabActionState.java, src/main/java/com/hollingsworth/arsnouveau/common/items/WarpScroll.java
allows SourceUtil#takeSource to extract from multiple ISpecialSourceProviders in order to reach the desired amount. Also short circuits if a Creative Source Jar is found.
split of #1555
=> feat: SourceUtil multi-provider take

src/main/java/com/hollingsworth/arsnouveau/api/spell/AbstractEffect.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectDelay.java
Fix randomize config overriding extend time, let delay use distinct duration down config
=> Fix randomize cfg and duration down for delay

src/main/java/com/hollingsworth/arsnouveau/common/entity/EntityWallSpell.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectBurst.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectKnockback.java
Add Extract to knockback to apply motion relative to caster pos instead of caster look, works best with orbit and burst.
Uniform wall and burst sensitive aoe adjustment to be the same as linger (1 aoe bonus if sensitive and 3 aoe bonus if not)
=> Knockback and Burst/Wall adjustments.

src/main/java/com/hollingsworth/arsnouveau/client/gui/radial_menu/GuiRadialMenu.java, src/main/java/com/hollingsworth/arsnouveau/client/keybindings/KeyHandler.java
This PR fixes an issue where binding LMB to a quickcast slot immediately fires the bound spell upon selecting an option in the selection HUD.
=> fix: radial selection fires quickcast bound to mouse buttons

src/main/java/com/hollingsworth/arsnouveau/common/block/tile/CraftingLecternTile.java
Actually fix this time, has been actively tested on legacy worlds
=> fix: crafting lectern tile migrations

src/main/java/com/hollingsworth/arsnouveau/ArsNouveau.java, src/main/java/com/hollingsworth/arsnouveau/api/registry/CasterTomeRegistry.java, src/main/java/com/hollingsworth/arsnouveau/common/event/EventHandler.java
Rather than trying to make use of a specific Overworld level from the started server for `CasterTomeRegistry` and doing so only for a `RegistryAccess`, it would make more sense for the latter to be retrieved directly from the started server itself independently of any level.
In situations such as when using the test server provided by NeoForge and ModDevGradle for unit testing, this prevents any such test runs from crashing and hanging due to the fact that the test server doesn't have any levels to speak of and returns `null` when trying to retrieve them, which up until now was never checked or accounted for.
=> Retrieve `RegistryAccess` directly from the server for caster tome registry

src/main/java/com/hollingsworth/arsnouveau/common/block/tile/StorageLecternTile.java
fixes issues with other mods reading the lectern (e.g. ae2 storage bus)
=> fix: invalidate lectern caps when connected inventories change

src/main/java/com/hollingsworth/arsnouveau/common/crafting/recipes/EnchantingApparatusRecipe.java
fixes some recipes creating items with useless damage components such as starbuncle charms.
=> fix: enchanting apparatus adding damage component when keepNbtOfReagent is true

src/main/java/com/hollingsworth/arsnouveau/api/spell/AbstractEffect.java, src/main/java/com/hollingsworth/arsnouveau/api/util/StackUtil.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectBlink.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectBubble.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectCraft.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectName.java, src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectWololo.java
There were several unnecessarily strict checks asking for the caster to be a real Player (e instanceof Player && !(e instanceof FakePlayer)). 
This commit relaxes these requirements where I deemed them unnecessary.
=> feat: let mobs do more

src/main/java/com/hollingsworth/arsnouveau/common/entity/pathfinding/pathjobs/AbstractPathJob.java
Fixing a bug in starbuncle's pathfinding that prevented the algorithm from walking up when checking path to goal. 
Before:
After:
The function `handleTargetNotPassable` should be returning the height of the block we are jumping to, so at the end it should return `pos.getY() + 1` even for small mobs.
Resolves a long standing issue: https://github.com/baileyholl/Ars-Nouveau/issues/1215
=> fix: bug in pathfinding preventing buncles from pathing upward

src/main/java/com/hollingsworth/arsnouveau/common/block/tile/PortalTile.java, src/main/java/com/hollingsworth/arsnouveau/common/items/WarpScroll.java
just sends the packet before setting position so that the warped player also gets it
=> fix: rotate when warping to unloaded (client-side) chunks

src/main/java/com/hollingsworth/arsnouveau/common/block/tile/EnchantingApparatusTile.java, src/main/java/com/hollingsworth/arsnouveau/common/block/tile/RuneTile.java
this PR is made with the assumption that these are indeed unintentional, which seems likely since the raw numbers used indicate intent that apparatus should take 210 ticks to craft and runes should take 40 ticks to recharge, rather than the 211 and 41 ticks that can be observed.
=> fix: apparatus crafting and rune recharge 1 tick longer than they should be

src/generated/resources/data/ars_nouveau/recipe/scry_ritual/amethyst_gems.json, src/main/java/com/hollingsworth/arsnouveau/common/datagen/ScryRitualProvider.java
this was a broken recipe entry and didnt provide much value due to the existence of the dowsing rod
=> fix: remove amethyst scry augment due to lack of #c:storage_blocks/amethyst

src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectWindburst.java
fixes block resolving causing windburst to spawn inside caster
sets explosion source to dummy wind charge so fall damage from impulse is negated
=> fix: windburst stuff

src/main/java/com/hollingsworth/arsnouveau/common/entity/Alakarkinos.java, src/main/java/com/hollingsworth/arsnouveau/common/entity/AmethystGolem.java, src/main/java/com/hollingsworth/arsnouveau/common/entity/EntityBookwyrm.java, src/main/java/com/hollingsworth/arsnouveau/common/entity/EntityDrygmy.java, src/main/java/com/hollingsworth/arsnouveau/common/entity/EntityWixie.java, src/main/java/com/hollingsworth/arsnouveau/common/entity/Starbuncle.java, src/main/java/com/hollingsworth/arsnouveau/common/entity/Whirlisprig.java
should prevent scavenger from apotheosis or other similar things duping charms
=> feat: use dropCustomDeathLoot rather than die to spawn helper charms

src/generated/resources/assets/ars_nouveau/lang/en_us.json
Update a likely typo in the chat message when using (consuming) the Annotated Codex
=> [Lang] Update typo in en_us.json

src/main/java/com/hollingsworth/arsnouveau/client/gui/book/GuiSpellBook.java
the previous PR was slightly broken, only allowing you to split on an empty cell once
=> fix: better spell splitting

src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectHarvest.java
previously it would spawn in the northwest corner
=> fix: make EffectHarvest spawn drops at bottom center of block

src/main/java/com/hollingsworth/arsnouveau/client/emi/EmiApparatusEnchantingRecipe.java, src/main/java/com/hollingsworth/arsnouveau/setup/registry/Documentation.java
In some packs, enchantments like elemental's soulbound are disabled and might lead to components failing. It covers the reported failing points but more might be discovered in the future
=> Check if enchantment is disabled before using orThrow()

src/main/java/com/hollingsworth/arsnouveau/client/events/ClientEvents.java
fixes tooltips not showing on imbuement chambers when playing on servers
=> fix: reload generic recipe registries on client

src/main/java/com/hollingsworth/arsnouveau/common/entity/EnchantedFallingBlock.java
currently causes a large area to be uninteractable
=> fix: set EnchantedFallingBlock#getPickRadius to 0 (1 by default)

src/main/java/com/hollingsworth/arsnouveau/common/block/tile/MobJarTile.java
known consequences include something adjacent to void trading and villagers losing trade offer data if they were not jarred at Master level
=> fix: jarred entities dont save when jar is removed

src/main/java/com/hollingsworth/arsnouveau/common/entity/goal/carbuncle/StarbyTransportBehavior.java
Fixes an issue where, if an item handler didn't allow extracting a stack, a Starbuncle would get stuck sitting next to that container and trying fruitlessly to extract it.
=> Fix Starby extraction logic

src/main/java/com/hollingsworth/arsnouveau/common/spell/effect/EffectGravity.java
Docs seem to imply it was not an intended feature to scale the gravity on the duration stat
=> Fix duration used instead of amplification

src/main/java/com/hollingsworth/arsnouveau/api/ArsNouveauAPI.java, src/main/java/com/hollingsworth/arsnouveau/common/command/DebugNumberCommand.java, src/main/java/com/hollingsworth/arsnouveau/common/event/EventHandler.java, src/main/java/com/hollingsworth/arsnouveau/common/network/Networking.java, src/main/java/com/hollingsworth/arsnouveau/common/network/PacketToggleDebug.java
Disables by default the numbers on the mana bar even in dev and adds a command to switch them on/off if needed. Needs op permission.
=> Command to enable/disable debug numbers

src/main/java/com/hollingsworth/arsnouveau/client/events/ClientEvents.java
previously set but never accessed
=> fix: show storage tooltips

src/main/java/com/hollingsworth/arsnouveau/client/gui/book/GuiSpellBook.java
Fixes a bug that happens when there are too many glyphs. With enough form/augments, the effect text was ending up on the bottom of right page, while the 4 'n 6th page had a constant y offset in excess
=> Fix Effect Text and glyph offset

src/main/java/com/hollingsworth/arsnouveau/client/gui/documentation/BaseDocScreen.java, src/main/java/com/hollingsworth/arsnouveau/common/items/Glyph.java, src/main/java/com/hollingsworth/arsnouveau/common/items/PerkItem.java, src/main/java/com/hollingsworth/arsnouveau/common/items/RitualTablet.java
Sometimes tooltips can be computed off the render thread, so it's not safe to use input constants.
=> fix: remove client methods in tooltips

src/main/java/com/hollingsworth/arsnouveau/common/mixin/perks/UnbreakablePerk.java, src/main/resources/ars_nouveau.mixins.json
Current implementation of unbreakability was ignored by most sources of damage, this mixin chains in the check with the vanilla UNBREAKABLE data component
=> Move UnbreakablePerk to mixin 

src/main/java/com/hollingsworth/arsnouveau/common/mixin/camera/ClientChunkCacheMixin.java
This fixes Sodium compatibility for the Oculus, by redirecting the storage instead of rewriting the whole call.
This *could* cause issues with other mods that do the same redirect, but I haven't found any that do; and if that's an issue, a WrapOperation could be used instead.
I have personally tested this PR on All The Mods 10.
=> fix: less invasive ClientChunkCache mixin

src/main/java/com/hollingsworth/arsnouveau/common/block/RuneBlock.java
The check would look at the first glyph in the spell, but since it's always a form and not a filter it would always break the loop immediately
=> Fix Rune-Filter check
